In [1]:
import numpy as np

X = np.array([
    [0,  1,  0,  0,  0, -1, -1, -1,  0],
    [0, -1, -1,  0,  0,  0,  1,  0,  0],
    [-1, -1, -1,  1,  0,  0,  0,  1, -1],
    [-1,  1, -1,  1, -1, -1,  0, -1,  0],
    [-1,  1,  1,  1, -1, -1, -1,  0, -1],
    [0, -1,  1,  1, -1,  1,  1,  0,  0],
    [1,  0, -1,  1, -1,  0,  0,  0,  1],
    [1, -1, -1,  1, -1,  0, -1, -1, -1]
])

wq = np.array([
    [-1,  0,  1],
    [ 1, -1,  0],
    [ 0,  1, -1],
    [-1,  0,  0],
    [ 1,  1,  0],
    [ 0, -1,  1],
    [-1,  1, -1],
    [ 0,  0,  1],
    [ 1, -1,  1]
])

wk = np.array([
    [ 0,  1, -1],
    [ 0, -1,  0],
    [-1, -1, -1],
    [ 0,  1, -1],
    [-1, -1, -1],
    [-1,  0,  0],
    [ 1,  0,  0],
    [ 1,  1, -1],
    [ 1,  1,  1]
])

wv = np.array([
    [ 1,  0, -1],
    [ 0,  1,  1],
    [-1, -1,  0],
    [ 1, -1,  1],
    [ 0,  0, -1],
    [-1,  1,  0],
    [ 1,  1, -1],
    [-1,  0,  1],
    [ 0, -1, -1]
])

In [2]:
Q = X @ wq
Q

array([[ 2, -1, -1],
       [-2,  1,  0],
       [-2,  1,  0],
       [ 0, -2, -2],
       [ 0,  0, -3],
       [-4,  1, -1],
       [-2, -3,  3],
       [-4, -1,  1]])

In [3]:
K = X @ wk
K

array([[-1, -2,  1],
       [ 2,  2,  1],
       [ 1,  2, -1],
       [ 2,  0,  3],
       [-1, -2, -1],
       [ 0,  2, -1],
       [ 3,  5,  1],
       [-1,  3,  0]])

In [4]:
V = X @ wv
V

array([[ 1, -1,  1],
       [ 2,  1, -2],
       [ 0,  0,  3],
       [ 3,  0,  3],
       [-1, -2,  6],
       [ 0, -1,  0],
       [ 3, -1,  0],
       [ 3, -1,  1]])

In [5]:
Qkt = Q @ K.T
Qkt

array([[ -1,   1,   1,   1,   1,  -1,   0,  -5],
       [  0,  -2,   0,  -4,   0,   2,  -1,   5],
       [  0,  -2,   0,  -4,   0,   2,  -1,   5],
       [  2,  -6,  -2,  -6,   6,  -2, -12,  -6],
       [ -3,  -3,   3,  -9,   3,   3,  -3,   0],
       [  1,  -7,  -1, -11,   3,   3,  -8,   7],
       [ 11,  -7, -11,   5,   5,  -9, -18,  -7],
       [  7,  -9,  -7,  -5,   5,  -3, -16,   1]])

In [6]:
d_k = 3
sqrt_dk = np.sqrt(d_k)
scaled_attention_logits = Qkt / sqrt_dk
scaled_attention_logits

array([[ -0.57735027,   0.57735027,   0.57735027,   0.57735027,
          0.57735027,  -0.57735027,   0.        ,  -2.88675135],
       [  0.        ,  -1.15470054,   0.        ,  -2.30940108,
          0.        ,   1.15470054,  -0.57735027,   2.88675135],
       [  0.        ,  -1.15470054,   0.        ,  -2.30940108,
          0.        ,   1.15470054,  -0.57735027,   2.88675135],
       [  1.15470054,  -3.46410162,  -1.15470054,  -3.46410162,
          3.46410162,  -1.15470054,  -6.92820323,  -3.46410162],
       [ -1.73205081,  -1.73205081,   1.73205081,  -5.19615242,
          1.73205081,   1.73205081,  -1.73205081,   0.        ],
       [  0.57735027,  -4.04145188,  -0.57735027,  -6.35085296,
          1.73205081,   1.73205081,  -4.61880215,   4.04145188],
       [  6.35085296,  -4.04145188,  -6.35085296,   2.88675135,
          2.88675135,  -5.19615242, -10.39230485,  -4.04145188],
       [  4.04145188,  -5.19615242,  -4.04145188,  -2.88675135,
          2.88675135,  -1.7320508

In [7]:
def softmax(x):
    # stabilitas numerik: kurangi nilai maksimum di tiap baris
    e_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return e_x / np.sum(e_x, axis=1, keepdims=True)

attention_weights = softmax(scaled_attention_logits)
attention_weights

array([[6.03393783e-02, 1.91461256e-01, 1.91461256e-01, 1.91461256e-01,
        1.91461256e-01, 6.03393783e-02, 1.07483269e-01, 5.99295045e-03],
       [3.98662408e-02, 1.25639215e-02, 3.98662408e-02, 3.95954371e-03,
        3.98662408e-02, 1.26498495e-01, 2.23802663e-02, 7.14999051e-01],
       [3.98662408e-02, 1.25639215e-02, 3.98662408e-02, 3.95954371e-03,
        3.98662408e-02, 1.26498495e-01, 2.23802663e-02, 7.14999051e-01],
       [8.85195720e-02, 8.73210636e-04, 8.79182756e-03, 8.73210636e-04,
        8.91249809e-01, 8.79182756e-03, 2.73324650e-05, 8.73210636e-04],
       [9.56692709e-03, 9.56692709e-03, 3.05641752e-01, 2.99455468e-04,
        3.05641752e-01, 3.05641752e-01, 9.56692709e-03, 5.40745075e-02],
       [2.52363219e-02, 2.48946354e-04, 7.95327477e-03, 2.47255310e-05,
        8.00766933e-02, 8.00766933e-02, 1.39754479e-04, 8.06243590e-01],
       [9.41020305e-01, 2.88588051e-05, 2.86627728e-06, 2.94549831e-02,
        2.94549831e-02, 9.09490723e-06, 5.03660566e-08, 2.

In [8]:
np.set_printoptions(formatter={'float': lambda x: f"{x:0.3f}"})

print(attention_weights)

[[0.060 0.191 0.191 0.191 0.191 0.060 0.107 0.006]
 [0.040 0.013 0.040 0.004 0.040 0.126 0.022 0.715]
 [0.040 0.013 0.040 0.004 0.040 0.126 0.022 0.715]
 [0.089 0.001 0.009 0.001 0.891 0.009 0.000 0.001]
 [0.010 0.010 0.306 0.000 0.306 0.306 0.010 0.054]
 [0.025 0.000 0.008 0.000 0.080 0.080 0.000 0.806]
 [0.941 0.000 0.000 0.029 0.029 0.000 0.000 0.000]
 [0.740 0.000 0.000 0.001 0.233 0.002 0.000 0.023]]


In [9]:
attention_output = attention_weights @ V
attention_output

array([[1.167, -0.426, 1.981],
       [2.249, -0.971, 1.100],
       [2.249, -0.971, 1.100],
       [-0.796, -1.880, 5.464],
       [-0.085, -0.981, 2.796],
       [2.365, -1.072, 1.335],
       [1.000, -1.000, 1.206],
       [0.579, -1.232, 2.166]])

In [11]:
np.random.seed(42)
wq2, wk2, wv2 = [np.random.randint(-1, 2, (9, 3)) for _ in range(3)]
wq3, wk3, wv3 = [np.random.randint(-1, 2, (9, 3)) for _ in range(3)]

In [15]:
def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / np.sum(e_x, axis=-1, keepdims=True)

def attention(X, Wq, Wk, Wv):
    d_k = Wq.shape[1]
    Q, K, V = X @ Wq, X @ Wk, X @ Wv
    scores = (Q @ K.T) / np.sqrt(d_k)
    weights = softmax(scores)
    return weights @ V

In [16]:
head2 = attention(X, wq2, wk2, wv2)
head3 = attention(X, wq3, wk3, wv3)

In [18]:
head2

array([[0.318, -0.560, -1.352],
       [-0.404, -0.818, -0.823],
       [-0.966, -1.932, -0.969],
       [0.009, -0.984, -0.997],
       [0.019, 0.851, -1.920],
       [-0.111, 0.171, -0.968],
       [0.480, -0.484, -1.483],
       [-0.001, 0.897, -1.815]])

In [19]:
head3

array([[-2.716, 2.349, 1.096],
       [-2.860, 1.814, 0.886],
       [-3.632, 2.502, 1.549],
       [-1.412, 2.551, 1.983],
       [-1.058, 2.012, 0.035],
       [-1.731, 1.885, -0.321],
       [-1.441, 2.192, 0.572],
       [-3.571, 0.524, -2.125]])

In [20]:
multi_head_concat = np.concatenate([attention_output, head2, head3], axis=1)
multi_head_concat

array([[1.167, -0.426, 1.981, 0.318, -0.560, -1.352, -2.716, 2.349,
        1.096],
       [2.249, -0.971, 1.100, -0.404, -0.818, -0.823, -2.860, 1.814,
        0.886],
       [2.249, -0.971, 1.100, -0.966, -1.932, -0.969, -3.632, 2.502,
        1.549],
       [-0.796, -1.880, 5.464, 0.009, -0.984, -0.997, -1.412, 2.551,
        1.983],
       [-0.085, -0.981, 2.796, 0.019, 0.851, -1.920, -1.058, 2.012,
        0.035],
       [2.365, -1.072, 1.335, -0.111, 0.171, -0.968, -1.731, 1.885,
        -0.321],
       [1.000, -1.000, 1.206, 0.480, -0.484, -1.483, -1.441, 2.192,
        0.572],
       [0.579, -1.232, 2.166, -0.001, 0.897, -1.815, -3.571, 0.524,
        -2.125]])

In [21]:
W_o = np.random.randint(-1, 2, (9, 9))
W_o

array([[ 0,  0,  0, -1,  0, -1, -1,  0,  0],
       [ 0,  1,  0,  1, -1,  1,  0, -1, -1],
       [-1,  1,  0, -1, -1, -1,  1,  1,  0],
       [ 1, -1,  0, -1, -1,  1,  0,  1,  1],
       [ 0, -1, -1,  0, -1,  0,  0,  1,  0],
       [ 1, -1, -1, -1, -1,  1, -1,  0,  0],
       [ 0,  1, -1, -1, -1,  1,  0,  0, -1],
       [ 0,  0,  1,  1,  1,  1, -1,  1,  0],
       [-1,  0,  0,  0,  1,  1, -1, -1,  1]])

In [22]:
attention_output_final = multi_head_concat @ W_o
attention_output_final

array([[-4.110, 0.433, 6.976, 2.525, 6.198, -3.877, -1.279, 3.419, 4.555],
       [-3.214, -0.685, 6.315, 1.581, 7.476, -5.708, -3.026, 1.778,
        4.312],
       [-4.585, 0.365, 9.035, 3.748, 11.421, -5.836, -4.231, 0.126,
        5.186],
       [-8.436, 4.145, 5.943, -1.598, 4.334, -4.414, 2.723, 6.935, 5.283],
       [-4.732, 1.807, 4.138, 1.279, 2.339, -4.605, 2.754, 6.623, 2.092],
       [-2.094, -0.559, 4.414, -0.076, 3.941, -6.018, -1.626, 4.672,
        2.371],
       [-2.782, 0.252, 5.600, 1.431, 5.486, -2.888, -1.074, 3.822, 3.493],
       [-1.857, -1.718, 5.012, 1.934, 1.954, -10.964, 5.003, 6.943,
        2.677]])

In [23]:
def xavier_uniform(shape, rng=np.random):
    fan_in, fan_out = shape[0], shape[1]
    limit = np.sqrt(6.0/(fan_in + fan_out))
    return rng.uniform(-limit, limit, size=shape)

W_o_xavier = xavier_uniform((9, 9), np.random)
W_o_xavier


array([[-0.362, -0.530, 0.105, 0.205, -0.558, 0.014, -0.316, 0.168,
        -0.376],
       [0.220, -0.131, 0.504, -0.419, -0.184, -0.446, 0.490, 0.436,
        -0.280],
       [0.185, 0.366, 0.064, 0.034, -0.298, -0.470, 0.459, 0.462, 0.154],
       [-0.186, -0.174, 0.261, 0.459, 0.447, 0.323, 0.164, -0.480,
        -0.391],
       [0.460, 0.123, -0.567, -0.460, 0.189, -0.572, -0.392, 0.056,
        0.222],
       [0.175, -0.318, 0.245, -0.303, -0.202, 0.285, 0.173, 0.403, 0.182],
       [0.079, -0.469, -0.153, -0.271, -0.296, 0.546, -0.123, 0.453,
        0.151],
       [0.340, 0.003, 0.089, -0.009, -0.352, 0.257, -0.253, -0.549,
        0.168],
       [-0.373, 0.509, 0.524, 0.479, -0.150, -0.560, 0.495, -0.083,
        0.539]])

In [24]:
attentioin_final_xavier = multi_head_concat @ W_o_xavier
attentioin_final_xavier

array([[-0.527, 2.307, 1.301, 2.540, -1.043, -2.179, 0.652, -2.414,
        0.064],
       [-1.209, 1.367, 1.035, 2.530, -1.500, -1.542, -0.238, -2.086,
        -0.229],
       [-1.717, 2.076, 2.011, 3.351, -2.046, -1.744, 0.330, -2.720,
        0.073],
       [0.271, 4.543, 1.114, 2.881, -1.598, -2.683, 2.560, -1.092, 2.545],
       [0.971, 2.431, -0.914, 0.974, -0.450, -1.985, -0.195, -1.471,
        0.764],
       [-0.292, 0.379, -0.306, 1.443, -1.447, -0.807, -1.334, -1.573,
        -0.598],
       [-0.513, 1.345, 0.428, 2.203, -0.743, -0.642, -0.335, -2.470,
        -0.018],
       [0.703, 1.932, -1.898, 0.791, 0.982, -2.116, -1.202, -1.847,
        -1.269]])

In [26]:
attentioin_final_xavier.shape

(8, 9)

In [27]:
def layer_norm(x, eps=1e-5):
    # normalisasi per token (per baris)
    mu  = x.mean(axis=1, keepdims=True)
    var = x.var(axis=1, keepdims=True)
    return (x - mu) / np.sqrt(var + eps), mu.squeeze(), np.sqrt(var + eps).squeeze()

residual = X + attentioin_final_xavier
residual

array([[-0.527, 3.307, 1.301, 2.540, -1.043, -3.179, -0.348, -3.414,
        0.064],
       [-1.209, 0.367, 0.035, 2.530, -1.500, -1.542, 0.762, -2.086,
        -0.229],
       [-2.717, 1.076, 1.011, 4.351, -2.046, -1.744, 0.330, -1.720,
        -0.927],
       [-0.729, 5.543, 0.114, 3.881, -2.598, -3.683, 2.560, -2.092,
        2.545],
       [-0.029, 3.431, 0.086, 1.974, -1.450, -2.985, -1.195, -1.471,
        -0.236],
       [-0.292, -0.621, 0.694, 2.443, -2.447, 0.193, -0.334, -1.573,
        -0.598],
       [0.487, 1.345, -0.572, 3.203, -1.743, -0.642, -0.335, -2.470,
        0.982],
       [1.703, 0.932, -2.898, 1.791, -0.018, -2.116, -2.202, -2.847,
        -2.269]])

In [28]:
normed, row_mean, row_std = layer_norm(residual)
normed

array([[-0.177, 1.595, 0.668, 1.240, -0.415, -1.402, -0.094, -1.511,
        0.096],
       [-0.653, 0.504, 0.260, 2.092, -0.867, -0.898, 0.794, -1.297,
        0.066],
       [-1.178, 0.644, 0.613, 2.217, -0.855, -0.710, 0.286, -0.699,
        -0.318],
       [-0.449, 1.646, -0.167, 1.091, -1.074, -1.436, 0.650, -0.904,
        0.645],
       [0.098, 1.995, 0.161, 1.197, -0.681, -1.522, -0.541, -0.692,
        -0.015],
       [-0.008, -0.261, 0.751, 2.098, -1.668, 0.365, -0.040, -0.995,
        -0.243],
       [0.285, 0.819, -0.374, 1.975, -1.102, -0.417, -0.226, -1.554,
        0.593],
       [1.392, 0.977, -1.087, 1.440, 0.465, -0.666, -0.712, -1.060,
        -0.749]])

In [29]:
row_mean

array([-0.144, -0.319, -0.265, 0.616, -0.208, -0.282, 0.029, -0.880])

In [30]:
row_std

array([2.164, 1.362, 2.082, 2.993, 1.824, 1.299, 1.607, 1.855])

## FFNN

In [1]:
import numpy as np
def xavier_uniform(shape, rng=np.random):
    fan_in, fan_out = shape[0], shape[1]
    limit = np.sqrt(6.0 / (fan_in + fan_out))
    return rng.uniform(-limit, limit, size=shape)

# === FFNN layer 1 ===
def ffnn_layer1(X, out_dim=18, bias_value=1.0, seed=42):
    """
    X         : numpy array (N, D_in) -> input hasil LayerNorm
    out_dim   : jumlah neuron layer FF pertama (default 18)
    bias_value: nilai bias (default 1)
    seed      : agar hasil acak reproducible
    """
    np.random.seed(seed)

    N, D_in = X.shape  # misal (8, 9)
    D_out = out_dim    # misal 18

    # Inisialisasi bobot dan bias
    W1 = xavier_uniform((D_in, D_out))
    b1 = np.full((D_out,), bias_value, dtype=float)

    # Linear transform (belum ReLU)
    Z = np.dot(X, W1) + b1  # (8×9) · (9×18) + (1×18) -> (8×18)

    return Z, W1, b1

In [2]:
np.set_printoptions(formatter={'float': lambda x: f"{x:0.3f}"})

In [4]:
X_attention_norm = np.array([
    [-0.177,  1.595,  0.668,  1.240, -0.415, -1.402, -0.094, -1.511,  0.096],
    [-0.653,  0.504,  0.260,  2.092, -0.867, -0.898,  0.794, -1.297,  0.066],
    [-1.178,  0.644,  0.613,  2.217, -0.855, -0.710,  0.286, -0.699, -0.318],
    [-0.449,  1.646, -0.167,  1.091, -1.074, -1.436,  0.650, -0.904,  0.645],
    [ 0.098,  1.995,  0.161,  1.197, -0.681, -1.522, -0.541, -0.692, -0.015],
    [-0.008, -0.261,  0.751,  2.098, -1.668,  0.365, -0.040, -0.995, -0.243],
    [ 0.285,  0.819, -0.374,  1.975, -1.102, -0.417, -0.226, -1.554,  0.593],
    [ 1.392,  0.977, -1.087,  1.440,  0.465, -0.666, -0.712, -1.060, -0.749]
], dtype=float)

# Jalankan layer FFNN pertama
Z, W1, b1 = ffnn_layer1(X_attention_norm, out_dim=18, bias_value=1.0, seed=42)

print("Z shape:", Z.shape)
print("W1 shape:", W1.shape)
print("W1:\n", np.round(W1, 4))
print("b1 shape:", b1.shape)
print("\nPreview output Z (belum ReLU):\n", np.round(Z, 4))

Z shape: (8, 18)
W1 shape: (9, 18)
W1:
 [[-0.118 0.425 0.219 0.093 -0.324 -0.324 -0.417 0.345 0.095 0.196 -0.452
  0.443 0.313 -0.271 -0.300 -0.298 -0.185 0.023]
 [-0.064 -0.197 0.105 -0.340 -0.196 -0.126 -0.041 0.269 -0.283 0.013
  0.087 -0.428 0.101 -0.311 -0.410 0.423 0.439 0.291]
 [-0.184 -0.379 0.174 -0.056 -0.356 -0.004 -0.439 0.386 -0.227 0.153
  -0.177 0.019 0.044 -0.297 0.443 0.259 0.414 0.372]
 [0.092 0.398 -0.388 -0.287 -0.429 -0.165 -0.105 -0.216 0.310 -0.135
  -0.206 0.040 -0.339 0.285 -0.401 0.459 0.257 -0.284]
 [-0.466 0.297 0.195 0.216 0.256 -0.402 -0.133 -0.362 0.342 0.116 -0.159
  -0.411 -0.178 -0.165 0.216 0.130 0.365 -0.026]
 [-0.359 0.201 0.246 0.058 0.256 -0.006 0.021 -0.068 -0.447 -0.370 -0.442
  0.129 -0.175 0.008 0.384 -0.236 -0.085 0.241]
 [-0.256 -0.399 -0.198 -0.319 0.405 0.290 0.126 0.350 0.286 -0.295 0.370
  0.037 0.290 0.373 -0.172 -0.368 -0.257 -0.069]
 [0.300 0.340 -0.465 0.010 -0.078 -0.262 -0.358 -0.153 0.418 -0.167 0.018
  0.191 -0.129 0.445 0.436 -0

In [5]:
Z1_relu = np.maximum(0, Z)
Z1_relu

array([[1.158, 0.000, 1.070, 0.000, 0.000, 1.173, 1.176, 1.779, 0.559,
        1.670, 1.512, 0.000, 1.218, 0.081, 0.000, 3.157, 2.311, 1.331],
       [1.311, 0.132, 0.206, 0.000, 0.067, 1.713, 1.604, 1.395, 1.153,
        0.848, 1.697, 0.591, 0.869, 1.411, 0.000, 2.562, 1.537, 0.637],
       [1.625, 0.412, 0.000, 0.000, 0.000, 1.613, 1.225, 1.169, 1.175,
        0.770, 1.420, 0.518, 0.370, 1.422, 0.000, 2.848, 2.039, 0.681],
       [1.527, 0.000, 0.419, 0.000, 0.000, 1.490, 1.844, 1.683, 0.735,
        1.119, 2.476, 0.089, 1.502, 1.136, 0.000, 2.600, 1.501, 0.984],
       [1.738, 0.542, 0.716, 0.000, 0.000, 0.829, 0.913, 1.645, 0.788,
        1.668, 1.415, 0.177, 1.152, 0.233, 0.000, 3.035, 2.254, 1.119],
       [1.481, 0.959, 0.497, 0.107, 0.000, 1.654, 0.953, 1.542, 0.473,
        0.678, 0.375, 1.807, 0.604, 1.218, 0.013, 1.942, 1.140, 0.898],
       [1.300, 0.778, 0.828, 0.000, 0.000, 1.144, 1.699, 1.189, 0.390,
        1.089, 1.121, 0.798, 0.987, 0.891, 0.000, 2.601, 1.280, 0.854],

In [7]:
Z1_relu.shape

(8, 18)

In [6]:
hidden_dim = Z1_relu.shape[1]                
D_out      = X_attention_norm.shape[1]       

# Inisialisasi W2, b2 dengan Xavier Uniform & bias=1
W2 = xavier_uniform((hidden_dim, D_out))
b2 = np.full((D_out,), 1.0, dtype=float)

# Linear layer-2 (tanpa aktivasi)
Z2 = Z1_relu @ W2 + b2    # shape: (N, D_out)

print("W2 shape:", W2.shape)   # (hidden_dim, D_out)
print("b2 shape:", b2.shape)   # (D_out,)
print("Z2 shape:", Z2.shape)   # (N, D_out)
print("W2:\n", np.round(W2, 4))
print("\nPreview Z2 (tanpa residual & layer norm):\n", np.round(Z2, 4))


W2 shape: (18, 9)
b2 shape: (9,)
Z2 shape: (8, 9)
W2:
 [[0.126 0.034 -0.386 0.316 -0.169 -0.296 -0.433 0.086 0.167]
 [-0.456 0.011 -0.258 0.137 -0.307 0.180 -0.107 0.412 -0.342]
 [-0.150 -0.364 0.400 0.356 -0.228 0.151 0.299 0.052 0.028]
 [-0.243 -0.384 0.374 0.378 0.126 -0.152 -0.142 0.213 0.374]
 [0.365 0.264 0.134 -0.392 -0.319 0.376 0.100 -0.463 -0.376]
 [0.154 -0.467 -0.320 0.046 0.181 0.143 -0.260 0.200 -0.248]
 [-0.165 0.232 0.141 0.329 0.149 0.064 -0.383 -0.125 -0.221]
 [-0.241 0.446 -0.101 0.370 0.124 0.278 0.003 0.072 -0.007]
 [-0.287 0.210 -0.207 -0.449 0.137 -0.304 0.415 0.428 0.391]
 [-0.122 -0.457 0.404 -0.068 0.440 0.437 0.333 -0.194 -0.108]
 [0.331 -0.173 -0.312 0.054 0.411 0.185 0.066 -0.380 0.108]
 [0.462 -0.339 0.017 0.356 0.227 0.186 0.191 -0.133 -0.195]
 [0.292 0.292 0.346 0.390 0.011 0.001 0.281 0.141 0.190]
 [0.279 0.368 -0.153 -0.117 -0.383 0.074 -0.438 -0.032 0.040]
 [-0.201 0.086 -0.443 -0.436 0.304 -0.132 -0.352 0.021 0.255]
 [-0.268 0.116 -0.391 -0.423 0.030

In [10]:
Z2_out = X_attention_norm + Z2
Z2_out

array([[0.315, 2.109, 0.757, 2.003, 1.814, 0.267, 0.813, 1.254, 3.065],
       [0.610, 1.807, -0.750, 2.972, 1.193, 0.596, 0.610, 1.089, 2.586],
       [-0.220, 1.792, -0.791, 2.490, 0.830, 0.292, -0.334, 2.216, 2.473],
       [0.976, 3.037, -1.000, 2.489, 1.296, 0.351, 0.672, 1.117, 3.309],
       [0.492, 2.759, -0.134, 1.984, 1.268, -0.121, 0.144, 2.296, 3.011],
       [1.284, 0.410, 0.010, 4.008, -0.429, 2.195, -0.094, 1.681, 1.114],
       [1.091, 1.712, -0.686, 3.562, 0.503, 1.478, 0.006, 0.801, 2.520],
       [0.361, 1.346, -0.386, 2.845, 1.473, 0.807, 0.701, 2.848, 1.284]])

In [11]:
def layer_norm(x, eps=1e-5):
    # normalisasi per token (per baris)
    mu  = x.mean(axis=1, keepdims=True)
    var = x.var(axis=1, keepdims=True)
    return (x - mu) / np.sqrt(var + eps), mu.squeeze(), np.sqrt(var + eps).squeeze()

Z2_norm, Z_row_mean, Z_row_std = layer_norm(Z2_out)
Z2_norm

array([[-1.200, 0.826, -0.702, 0.707, 0.494, -1.255, -0.638, -0.140,
        1.908],
       [-0.542, 0.576, -1.813, 1.665, 0.002, -0.555, -0.542, -0.095,
        1.304],
       [-0.973, 0.670, -1.440, 1.240, -0.116, -0.555, -1.066, 1.016,
        1.226],
       [-0.296, 1.291, -1.819, 0.870, -0.050, -0.778, -0.530, -0.188,
        1.501],
       [-0.683, 1.234, -1.213, 0.578, -0.027, -1.201, -0.978, 0.843,
        1.447],
       [0.117, -0.551, -0.856, 2.196, -1.191, 0.812, -0.935, 0.420,
        -0.013],
       [-0.107, 0.404, -1.569, 1.926, -0.591, 0.212, -0.999, -0.346,
        1.069],
       [-0.886, 0.093, -1.629, 1.581, 0.219, -0.443, -0.548, 1.584,
        0.030]])

In [12]:
print("Z1 mean:", Z_row_mean)
print("Z1 std :", Z_row_std)

Z1 mean: [1.377 1.191 0.972 1.361 1.300 1.131 1.221 1.253]
Z1 std : [0.885 1.070 1.225 1.298 1.182 1.310 1.215 1.007]


In [13]:
N, D = Z2_norm.shape
M = D

W_linear = xavier_uniform((D, M))
b_linear = np.ones((M,), dtype=float)

y_linear = Z2_norm @ W_linear + b_linear

print("W_linear shape:", W_linear.shape)
print("Y_linear:", y_linear.shape)
print("Preview Y_linear:\n", np.round(y_linear, 3))

W_linear shape: (9, 9)
Y_linear: (8, 9)
Preview Y_linear:
 [[1.729 1.044 1.752 1.690 0.344 2.493 1.307 1.145 1.919]
 [2.483 1.251 1.117 0.565 0.392 1.841 1.198 1.515 1.548]
 [1.278 1.417 1.769 1.289 0.228 1.587 1.278 0.751 2.493]
 [2.209 0.847 1.209 1.393 0.252 2.414 0.740 1.158 1.370]
 [1.321 1.285 2.038 2.211 0.098 2.203 1.023 0.459 2.427]
 [1.781 1.575 0.708 -0.836 0.476 -0.490 0.654 1.388 1.558]
 [2.329 1.100 0.751 -0.252 0.317 0.874 0.514 1.640 1.158]
 [1.174 1.956 1.519 0.922 0.872 0.978 2.063 0.756 2.713]]


In [14]:
W_linear

array([[0.525, 0.275, 0.063, 0.129, -0.093, -0.291, -0.166, 0.298,
        -0.561],
       [-0.443, -0.524, -0.530, 0.410, 0.235, -0.030, -0.464, -0.010,
        -0.031],
       [-0.377, -0.076, -0.117, 0.134, 0.156, -0.525, -0.145, 0.145,
        0.004],
       [0.412, 0.183, -0.389, -0.496, 0.164, -0.547, 0.099, 0.508, 0.087],
       [-0.129, 0.165, -0.048, 0.053, 0.510, -0.132, 0.533, 0.468,
        -0.351],
       [-0.497, -0.461, -0.556, -0.468, 0.211, -0.495, -0.209, 0.398,
        -0.550],
       [0.363, -0.252, -0.441, 0.227, 0.149, 0.436, 0.271, 0.350, -0.252],
       [-0.372, 0.289, 0.354, 0.566, -0.101, -0.148, 0.319, -0.184,
        0.497],
       [0.414, -0.082, 0.290, 0.294, -0.458, 0.465, 0.006, 0.377, -0.208]])

## Classification

In [15]:
CLS = y_linear[0]       
M   = CLS.shape[0]

np.random.seed(77)

# Linear untuk [CLS] (Xavier)
H_cls = 9
W_cls = xavier_uniform((M, H_cls))
b_cls = np.ones((H_cls,), dtype=float)

cls_linear = CLS @ W_cls + b_cls      
cls_tanh   = np.tanh(cls_linear)      

print("CLS shape:", CLS.shape)
print("W_cls shape:", W_cls.shape)
print("cls_linear:\n", np.round(cls_linear, 2))
print("cls_tanh:\n", np.round(cls_tanh, 2))

CLS shape: (9,)
W_cls shape: (9, 9)
cls_linear:
 [2.180 -0.200 1.640 -1.630 -1.740 1.470 -0.020 1.950 -0.720]
cls_tanh:
 [0.970 -0.200 0.930 -0.930 -0.940 0.900 -0.020 0.960 -0.620]


In [19]:
CLS

array([1.729, 1.044, 1.752, 1.690, 0.344, 2.493, 1.307, 1.145, 1.919])

In [17]:
W_cls

array([[0.484, 0.164, 0.293, -0.416, -0.477, 0.333, -0.201, 0.047,
        -0.300],
       [0.052, -0.115, 0.248, 0.389, 0.102, -0.235, -0.253, 0.237,
        -0.089],
       [-0.511, 0.285, -0.055, -0.374, -0.520, -0.240, -0.500, 0.290,
        -0.504],
       [-0.079, -0.157, -0.402, 0.054, -0.065, -0.536, 0.373, -0.262,
        -0.382],
       [0.167, -0.453, -0.169, -0.132, -0.063, 0.551, 0.265, -0.217,
        0.456],
       [0.327, -0.275, -0.220, -0.428, -0.090, 0.508, -0.154, -0.075,
        0.482],
       [0.516, -0.283, 0.242, -0.520, -0.422, 0.008, 0.103, -0.200,
        -0.410],
       [-0.280, 0.413, 0.212, 0.576, -0.208, -0.054, 0.424, 0.160,
        -0.194],
       [0.048, -0.448, 0.365, -0.322, 0.017, 0.030, -0.257, 0.467,
        -0.092]])

In [18]:
feat = cls_tanh                
F    = feat.shape[0]
num_labels = 2

np.random.seed(1313)

# Bobot classifier (Xavier) dan bias=1 
W_clf = xavier_uniform((F, num_labels))
b_clf = np.ones((num_labels,), dtype=float)

logits = feat @ W_clf + b_clf      # (2,)
# Softmax
logits_shift = logits - logits.max()
probs = np.exp(logits_shift) / np.exp(logits_shift).sum()

print("W_clf shape:", W_clf.shape)
print("logits:", np.round(logits, 3))
print("softmax probs (Class A, Class B):", np.round(probs, 4))

W_clf shape: (9, 2)
logits: [0.253 -0.328]
softmax probs (Class A, Class B): [0.641 0.358]


In [20]:
W_clf

array([[0.727, -0.693],
       [0.518, 0.713],
       [-0.437, -0.004],
       [-0.328, 0.569],
       [0.229, 0.489],
       [-0.649, 0.133],
       [0.671, 0.721],
       [-0.201, 0.468],
       [0.398, 0.123]])